repository:
  url: "https://gitlab.home.martinbranda.com/louis/backup-portainer-github"

title:
  pattern: 'v{{ .Version }}'
  content: 'ğŸ“¦ Release {{ .Version }} â€“ {{ .Time.Format "2006-01-02" }}'

style: github

template: CHANGELOG.tpl.md

sections:
  - title: "âœ¨ Nouvelles fonctionnalitÃ©s"
    labels: ["feat", "feature"]
  - title: "ğŸ› Corrections de bugs"
    labels: ["fix", "bugfix", "bug"]
  - title: "ğŸ§¼ Maintenance"
    labels: ["chore", "refactor", "style"]
  - title: "ğŸ“ Documentation"
    labels: ["docs"]
  - title: "ğŸ” IntÃ©gration continue"
    labels: ["ci", "test"]
  - title: "ğŸ“¦ DÃ©pendances"
    labels: ["deps", "dependencies"]

replacements:
  - search: 'Merge pull request #[0-9]* from .*'
    replace: ''
  - search: 'Closes #[0-9]*'
    replace: ''

sort:
  commits: asc
  sections: asc